### ISSUE TITLE
Investigate errors in console

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#1039] opened 2022-11-11 10:21 UTC

**Comment by salboaie** [comment] 2022-11-11 10:23
![image](https://user-images.githubusercontent.com/1595518/201320220-98af7ccb-1e6b-4f44-98ae-70482342a76d.png)

**Comment by salboaie** [comment] 2022-11-11 10:23
![image](https://user-images.githubusercontent.com/1595518/201320403-ebf69a75-6204-4de6-9f46-0fb2b13bd1d8.png)

**Comment by skutner** [comment] 2022-11-15 08:45
Errors caused by apihub restart (due to memory leak). Fixed in #1040

**Closed by skutner** 2022-11-15 08:45 UTC
