### ISSUE TITLE
Inaccuracies in Scandit scan

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#286] opened 2021-07-09 06:41 UTC
We have observed the following inaccuracies in the scandit scanner:
1. Scanning doesn't allow scanning laser etched codes.
2. Scanning doesn't happen when API key is changed - unless the app is restarted 

3. Post scanning resolution is not always accurate.
Please see video for point 3  - https://youtu.be/vK6X1OVW-pk

**Comment by rite2bala** [comment] 2021-07-12 15:31
Laser etched codes for reference.  


![Laser etched2](https://user-images.githubusercontent.com/44022980/125314805-260bd600-e354-11eb-9d44-5aa6f1488437.jpg)


![Laser etched](https://user-images.githubusercontent.com/44022980/125314777-20ae8b80-e354-11eb-9f48-33bde44f00cb.jpg)

**Comment by rite2bala** [comment] 2021-07-12 15:35
@fp-prg-mdc

**Comment by vz-msd** [comment] 2021-07-13 10:24
@rite2bala Laser edge codes are working. The issue is if you are using these examples and scanning from your screen, as these pictures have bad resolution. I tried to scan printed code, and it was scanned correctly and returned standard "data-matrix" values encoded in the code.

**Comment by rite2bala** [comment] 2021-07-13 10:55
As discussed during the meeting - We suspected that it could be an issue with the API Key.

Lets communicate to check if it works fine upon changing the key.

**Comment by mppub** [comment] 2021-07-20 10:29
@rite2bala Hello, you are leaking the testing scandit API key on publicly accessible video - please delete the video or amend it so the key or the parts of it is not visible. Thank you:).

I have a question about 3) you mean the failed Serial number when accessing the product from the history right? I will look at it, it is probably not related to Scandit, I will keep you updated

**Comment by mppub** [comment] 2021-07-20 14:23
Hi @rite2bala  about the point 3) I have tested it with a fresh installment and it should work fine (after next release), the issue was that the serial number check after the scanning should give you an "serial number error", which is now happening. so the history was working fine actually.

regards

**Comment by rite2bala** [comment] 2021-07-21 12:47
Thank you @mppub. Will wait for the next release. 

Deleted the unlisted video as suggested.

**Comment by rite2bala** [comment] 2021-07-25 12:20
Do let us know your timelines for the next release.

**Comment by mppub** [comment] 2021-08-03 11:55
Hello @rite2bala and @UnHynek , so to sum up: the points 1. and 3. are basically fine without any changes.

About the point 2. that is valid point but Dan told me that we would need to reinitialize the Scandit app that would probably mean to restart the whole app which is not ideal, right @fp-prg-mdc @vz-msd ? I am putting this into backlog since the guys are not working on this issue right now.

**Comment by rite2bala** [comment] 2021-08-04 05:05
Hi @mppub 
Can we discuss over a call?

I have a few doubts regarding point 3.

**Comment by rite2bala** [comment] 2021-08-06 09:30
Here is the summary  of what I wanted to share:
1.	I have re uploaded the video: https://youtu.be/tdYyeMxKASw
2.	Here are the points to note in the video:
a.	We are using a chrome browser on a Mac, opened a new session and loaded the app 
b.	At 40 seconds , we change the settings – network set to epiqa and add the API key
c.	At 1:08 we are scanning a code .. 2d data matrix .. this is a valid code , contains all the details 
d.	At 1:10 it is observed that the product is scanned using the Scandit scanner 
e.	At 1:14 the product is resolved – Batch ID is ENT00921 – 
And the actual result observed is : **The product name, company name, serial number check, ePI button are all missing from the screen**
f.	But this is not the expected result ,as the product has all the details 
g.	In order to check if there is any issue – I navigate to the history page 
h.	At 1:40 – I navigate to the history page and click on the only one item present in history 
i.	It opens the product 
j.	At 1:45 – verifying that it is the same batch 
k.	Now  when the product was opened from history - we observe that the serial number check is corrected – but the product information still doesn’t appear. 

l.	Expected result:
**Serial number check must be failed 
Product details like name of the product and company must be visible at scan.**

**Comment by rite2bala** [comment] 2021-08-06 10:29
Hi @mppub 
In order to check the persistence of the issue in the UAT environment I have done the test again 

here are the results 
![image](https://user-images.githubusercontent.com/44022980/128496828-972ef6c9-f24d-4a70-9ad2-c4f6d675743a.png)

Please let me  know if you require any further inputs to identify the issue

**Problem statement:**
Investigate and resolve - why we do not get the extra Product information  button and the company/ product name in the step 2 - while scanning with the API Key

cc: @UnHynek @nhrishi @fp-prg-mdc

**Comment by mppub** [comment] 2021-08-06 11:02
Hi @rite2bala thanks for reporting this issue - it is not an issue with Scandit as you can see the Scan giving you the correct results(no serial number) thus the issue with the page after the scan - I will close this issue and open a new one regarding this issue

**Closed by mppub** 2021-08-06 11:02 UTC
Labels: bug, Mobile App

**Comment by rite2bala** [comment] 2021-08-06 11:12
Please share the details of the new ticket.

**Comment by mppub** [comment] 2021-08-06 12:33
@rite2bala the issue has been transformed to #318
